version: '3'

vars:
  BINARY_NAME: tq
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "none"
  BUILD_DATE:
    sh: date -u +%Y-%m-%dT%H:%M:%SZ

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the tq binary
    cmds:
      - go build -ldflags "-X main.version={{.VERSION}} -X main.commit={{.COMMIT}} -X main.date={{.BUILD_DATE}}" -o {{.BINARY_NAME}} cmd/tq/main.go
    sources:
      - "**/*.go"
    generates:
      - "{{.BINARY_NAME}}"

  install:
    desc: Install tq to $GOPATH/bin
    cmds:
      - go install -ldflags "-X main.version={{.VERSION}} -X main.commit={{.COMMIT}} -X main.date={{.BUILD_DATE}}" ./cmd/tq

  install-man:
    desc: Install man page to /usr/local/share/man/man1
    cmds:
      - sudo mkdir -p /usr/local/share/man/man1
      - sudo cp docs/man/tq.1 /usr/local/share/man/man1/
      - sudo chmod 644 /usr/local/share/man/man1/tq.1
      - echo "Man page installed. Try 'man tq'"

  uninstall-man:
    desc: Uninstall man page
    cmds:
      - rm -f /usr/local/share/man/man1/tq.1
      - echo "Man page uninstalled"

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  test-coverage:
    desc: Run tests with coverage
    cmds:
      - go test -v -coverprofile=coverage.txt -covermode=atomic ./...
      - go tool cover -html=coverage.txt -o coverage.html

  lint:
    desc: Run linters
    cmds:
      - go fmt ./...
      - go vet ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f {{.BINARY_NAME}}
      - rm -f coverage.txt coverage.html
      - rm -rf dist/

  deps:
    desc: Download dependencies
    cmds:
      - go mod download
      - go mod tidy

  example:
    desc: Run example conversions
    cmds:
      - echo "Converting JSON to TOON..."
      - ./{{.BINARY_NAME}} -i json -o toon examples/data.json
      - echo ""
      - echo "Querying TOON data..."
      - ./{{.BINARY_NAME}} '.users[] | select(.active == true)' examples/data.toon

  dev:
    desc: Build and run a quick test
    deps:
      - build
    cmds:
      - ./{{.BINARY_NAME}} --version
      - echo '{"name":"test","value":42}' | ./{{.BINARY_NAME}} -i json -o toon

  release:
    desc: Build release binaries for multiple platforms
    cmds:
      - mkdir -p dist
      - GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version={{.VERSION}} -X main.commit={{.COMMIT}} -X main.date={{.BUILD_DATE}}" -o dist/{{.BINARY_NAME}}-linux-amd64 cmd/tq/main.go
      - GOOS=linux GOARCH=arm64 go build -ldflags "-X main.version={{.VERSION}} -X main.commit={{.COMMIT}} -X main.date={{.BUILD_DATE}}" -o dist/{{.BINARY_NAME}}-linux-arm64 cmd/tq/main.go
      - GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.version={{.VERSION}} -X main.commit={{.COMMIT}} -X main.date={{.BUILD_DATE}}" -o dist/{{.BINARY_NAME}}-darwin-amd64 cmd/tq/main.go
      - GOOS=darwin GOARCH=arm64 go build -ldflags "-X main.version={{.VERSION}} -X main.commit={{.COMMIT}} -X main.date={{.BUILD_DATE}}" -o dist/{{.BINARY_NAME}}-darwin-arm64 cmd/tq/main.go
      - GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version={{.VERSION}} -X main.commit={{.COMMIT}} -X main.date={{.BUILD_DATE}}" -o dist/{{.BINARY_NAME}}-windows-amd64.exe cmd/tq/main.go
